### ISSUE TITLE
CIM-Identities/WebDataEntry Page Not Found

### ISSUE THREAD

**Issue by swathirise123** [epri-dev/CIM-Identities#3]
Hi, When I'm going through "Launching-the-Executables" documentation in https://github.com/epri-dev/CIM-Identities/wiki/Launching-the-Executables, I figured out that "CIM-Identities/WebDataEntry" hyperlink found in the following screenshot is not working.
![image](https://user-images.githubusercontent.com/37460450/38223892-f2b21806-36b2-11e8-8f15-8f6f2aa3ca02.png)

I'm getting an error as shown below.
![image](https://user-images.githubusercontent.com/37460450/38224010-87f23f18-36b3-11e8-951c-9a8c1ffb89fb.png)

**Comment by DanielRLowe** [comment]
Yeah, I need to go back and update the documentation (you'll have to forgive me a bit as this was a project I did as an intern a while back now).  That particular version had web capabilities, but wasn't a SOAP web service, so it was eventually replaced.  You can find it in prior commit history if you're interested.

**Comment by DanielRLowe** [comment]
Okay, documentation links should be working properly now.  Thanks.
